#!/usr/bin/env python3
"""
sync-harnesses.py — generate per-harness native config from the single source of truth.

AI Desk keeps ONE editable copy of every capability:

    AGENTS.md                 the instructions (source of truth)
    agents/<name>.md          assistants   (Markdown + YAML: name, description, [tools])
    skills/<name>/SKILL.md    quick tools  (Markdown + YAML: name, description)
    commands/<name>.md        shortcuts    (Markdown + YAML: description; body uses $ARGUMENTS)
    (permission posture)      defined as data in this file

From those, this script generates each supported harness's *native* directories so the
assistants/tools/commands AUTO-REGISTER in that tool (Claude Code, opencode, Cursor, Gemini
CLI, OpenAI Codex, GitHub Copilot). Generated files are committed to the repo, so END USERS
run nothing — they clone and it works. Only CONTRIBUTORS run this, after editing a source file.

Usage:
    python3 scripts/sync-harnesses.py           # (re)generate all adapters
    python3 scripts/sync-harnesses.py --check    # verify adapters match source; exit 1 on drift

Dependencies: Python 3.8+ standard library only. No pip install.
"""

from __future__ import annotations

import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

GEN_NOTE = "GENERATED by scripts/sync-harnesses.py — DO NOT EDIT. Edit the source, then re-run."

# --- Canonical permission posture --------------------------------------------
# One definition, rendered into each harness's own config format below.
DENY_READ = [
    "~/.ssh/**", "~/.aws/**", "~/.config/gcloud/**", "~/.config/gh/**",
    "~/.gnupg/**", "~/.kube/**", "~/.docker/config.json", "~/.npmrc", "~/.netrc",
    "**/.env", "**/.env.*", "**/*.pem", "**/*.key", "**/id_rsa", "**/id_ed25519",
    "**/credentials",
]
# Write/edit destinations that must never be touched. Each harness also blocks its own
# global config dir; that is added per-harness where the concept exists.
DENY_WRITE = [
    "~/.ssh/**", "~/.bashrc", "~/.zshrc", "~/.profile", "~/.bash_profile", "**/.git/**",
]


# --- Tiny front-matter parser (no YAML dependency) ---------------------------
def parse_md(text):
    """Return (meta: dict, body: str) for a Markdown file with optional YAML front matter."""
    meta = {}
    body = text
    if text.startswith("---\n"):
        end = text.find("\n---\n", 4)
        if end == -1 and text.rstrip().endswith("\n---"):
            end = text.rstrip().rfind("\n---")
        if end != -1:
            fm = text[4:end]
            body = text[end + len("\n---\n"):]
            for line in fm.splitlines():
                line = line.rstrip()
                if not line or line.lstrip().startswith("#"):
                    continue
                if ":" in line:
                    key, val = line.split(":", 1)
                    meta[key.strip()] = val.strip()
    return meta, body


def read(path):
    with open(os.path.join(ROOT, path), "r", encoding="utf-8") as fh:
        return fh.read()


def toml_str(value):
    """Escape a Python string as a TOML basic (single-line) string."""
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return '"' + escaped + '"'


def toml_multiline(value):
    """Emit a TOML multi-line literal string; fall back to basic if it contains the delimiter."""
    if "'''" not in value:
        return "'''\n" + value.rstrip("\n") + "\n'''"
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return '"""\n' + escaped.rstrip("\n") + '\n"""'


def yaml_fm(pairs):
    """Build a YAML front-matter block from (key, value) pairs (values single-line).

    No generated-marker comment is injected here: a comment line inside YAML front matter can trip
    strict per-harness parsers, and breaking front matter would defeat auto-registration. Generated
    Markdown is instead flagged via .gitattributes (linguist-generated) and documented in
    docs/harnesses.md; the --check drift guard reverts any hand edit.
    """
    lines = ["---"]
    for key, val in pairs:
        lines.append(f"{key}: {val}")
    lines.append("---")
    return "\n".join(lines) + "\n"


# --- Source discovery --------------------------------------------------------
def list_agents():
    d = os.path.join(ROOT, "agents")
    return sorted(f for f in os.listdir(d) if f.endswith(".md")) if os.path.isdir(d) else []


def list_skills():
    d = os.path.join(ROOT, "skills")
    if not os.path.isdir(d):
        return []
    return sorted(n for n in os.listdir(d) if os.path.isfile(os.path.join(d, n, "SKILL.md")))


def list_commands():
    d = os.path.join(ROOT, "commands")
    return sorted(f for f in os.listdir(d) if f.endswith(".md")) if os.path.isdir(d) else []


# --- Adapter builders --------------------------------------------------------
def build():
    """Return {relative_path: file_content} for every generated adapter file."""
    files = {}

    # ---- Agents (assistants) ----
    for fname in list_agents():
        name = fname[:-3]
        meta, body = parse_md(read(f"agents/{fname}"))
        desc = meta.get("description", "")
        tools = meta.get("tools")

        # Claude Code — also serves Cursor & Copilot via their .claude/agents compat.
        claude_pairs = [("name", name), ("description", desc)]
        if tools:
            claude_pairs.append(("tools", tools))
        files[f".claude/agents/{fname}"] = yaml_fm(claude_pairs) + body

        # opencode — filename is the name; declare it a delegatable subagent.
        files[f".opencode/agents/{fname}"] = yaml_fm(
            [("description", desc), ("mode", "subagent")]
        ) + body

        # Gemini CLI — needs name + description.
        files[f".gemini/agents/{fname}"] = yaml_fm(
            [("name", name), ("description", desc)]
        ) + body

        # OpenAI Codex — TOML with developer_instructions.
        files[f".codex/agents/{name}.toml"] = (
            f"# {GEN_NOTE}\n"
            f"name = {toml_str(name)}\n"
            f"description = {toml_str(desc)}\n"
            f"developer_instructions = {toml_multiline(body)}\n"
        )

    # ---- Skills (quick tools) ----
    # SKILL.md is a shared standard. .claude/skills covers Claude/opencode/Cursor/Copilot;
    # .agents/skills covers opencode/Cursor/Gemini/Codex. Together = all six (deduped by name).
    for name in list_skills():
        src_dir = os.path.join(ROOT, "skills", name)
        for rel in sorted(os.listdir(src_dir)):
            if not os.path.isfile(os.path.join(src_dir, rel)):
                continue
            content = read(f"skills/{name}/{rel}")
            files[f".claude/skills/{name}/{rel}"] = content
            files[f".agents/skills/{name}/{rel}"] = content

    # ---- Commands (shortcuts) ----
    for fname in list_commands():
        name = fname[:-3]
        meta, body = parse_md(read(f"commands/{fname}"))
        desc = meta.get("description", "")

        # Claude Code & opencode use the same shape ($ARGUMENTS supported) — copy verbatim.
        verbatim = yaml_fm([("description", desc)]) + body
        files[f".claude/commands/{fname}"] = verbatim
        files[f".opencode/commands/{fname}"] = verbatim

        # Cursor — the whole file body is the prompt; no front matter, no arg placeholder.
        cursor_body = body.replace("$ARGUMENTS", "").rstrip() + "\n"
        files[f".cursor/commands/{fname}"] = (
            f"<!-- {GEN_NOTE} -->\n\n{cursor_body}"
        )

        # Gemini CLI — TOML with a prompt; its argument token is {{args}}.
        gem_prompt = body.replace("$ARGUMENTS", "{{args}}")
        files[f".gemini/commands/{name}.toml"] = (
            f"# {GEN_NOTE}\n"
            f"description = {toml_str(desc)}\n"
            f"prompt = {toml_multiline(gem_prompt)}\n"
        )

        # GitHub Copilot — a .prompt.md file (front matter + body).
        files[f".github/prompts/{name}.prompt.md"] = (
            yaml_fm([("description", desc)]) + body
        )

    # ---- Permission / settings configs (one posture, five formats) ----
    files[".claude/settings.json"] = build_claude_settings()
    files[".opencode/opencode.json"] = build_opencode_config()
    files[".cursor/permissions.json"] = build_cursor_permissions()
    files[".gemini/settings.json"] = build_gemini_settings()
    files[".codex/config.toml"] = build_codex_config()

    return files


def dump_json(data):
    return json.dumps(data, indent=2, ensure_ascii=False) + "\n"


def build_claude_settings():
    # No "_generated" key here: this file has a strict $schema. It's listed as generated in
    # docs/harnesses.md, and the --check drift guard reverts any hand edit.
    deny = [f"Read({p})" for p in DENY_READ]
    deny += [f"Write({p})" for p in DENY_WRITE] + [f"Edit({p})" for p in DENY_WRITE]
    deny += ["Write(~/.claude/**)", "Edit(~/.claude/**)"]
    data = {
        "$schema": "https://json.schemastore.org/claude-code-settings.json",
        "permissions": {
            "allow": ["Read", "Glob", "Grep", "Write", "Edit", "WebSearch", "WebFetch"],
            "deny": deny,
            "ask": ["Bash"],
        },
    }
    return dump_json(data)


def build_opencode_config():
    read_perm = {"*": "allow"}
    for p in DENY_READ:
        read_perm[p] = "deny"
    edit_perm = {"*": "allow"}
    for p in DENY_WRITE + ["~/.config/opencode/**"]:
        edit_perm[p] = "deny"
    data = {
        "$schema": "https://opencode.ai/config.json",
        "permission": {
            "read": read_perm,
            "edit": edit_perm,
            "glob": "allow",
            "grep": "allow",
            "webfetch": "allow",
            "websearch": "allow",
            "bash": "ask",
        },
    }
    return dump_json(data)


def build_cursor_permissions():
    # Cursor's model is a terminal/MCP allowlist, not a file-read deny list. The file-read
    # protection above is carried by the instructions (AGENTS.md) in Cursor. Here we make the
    # highest-risk action (running terminal commands) require explicit approval — the analog of
    # "Bash asks first".
    data = {
        "_generated": GEN_NOTE,
        "autoRun": {"block_instructions": ["*"]},
        "terminalAllowlist": [],
    }
    return dump_json(data)


def build_gemini_settings():
    # Also make Gemini read AGENTS.md natively (it does not by default).
    data = {
        "_generated": GEN_NOTE,
        "context": {"fileName": ["AGENTS.md", "GEMINI.md"]},
        "tools": {"autoAccept": False},
    }
    return dump_json(data)


def build_codex_config():
    # Codex uses a sandbox + approval model rather than path denies; pick safe defaults.
    return (
        f"# {GEN_NOTE}\n"
        '# Codex reads AGENTS.md natively for project instructions.\n'
        'approval_policy = "on-request"\n'
        'sandbox_mode = "workspace-write"\n'
    )


# --- Directories fully owned by the generator (for orphan pruning) -----------
MANAGED_DIRS = [
    ".claude/agents", ".claude/skills", ".claude/commands",
    ".opencode/agents", ".opencode/commands",
    ".agents/skills",
    ".cursor/commands",
    ".gemini/agents", ".gemini/commands",
    ".codex/agents",
    ".github/prompts",
]
MANAGED_FILES = [
    ".claude/settings.json", ".opencode/opencode.json", ".cursor/permissions.json",
    ".gemini/settings.json", ".codex/config.toml",
]


def existing_managed():
    """All files currently on disk under managed dirs, plus managed individual files."""
    out = set()
    for d in MANAGED_DIRS:
        base = os.path.join(ROOT, d)
        for dirpath, _dirs, names in os.walk(base):
            for n in names:
                out.add(os.path.relpath(os.path.join(dirpath, n), ROOT))
    for f in MANAGED_FILES:
        if os.path.isfile(os.path.join(ROOT, f)):
            out.add(f)
    return out


def main():
    check = "--check" in sys.argv[1:]
    files = build()
    on_disk = existing_managed()
    wanted = set(files)

    missing_or_diff = []
    for rel, content in sorted(files.items()):
        path = os.path.join(ROOT, rel)
        cur = None
        if os.path.isfile(path):
            with open(path, "r", encoding="utf-8") as fh:
                cur = fh.read()
        if cur != content:
            missing_or_diff.append(rel)
    orphans = sorted(on_disk - wanted)

    if check:
        problems = sorted(missing_or_diff) + [f"(stale) {o}" for o in orphans]
        if problems:
            print("Harness adapters are OUT OF SYNC with the source. Run: python3 scripts/sync-harnesses.py")
            for p in problems:
                print(f"  - {p}")
            sys.exit(1)
        print(f"Harness adapters in sync ({len(files)} generated files).")
        sys.exit(0)

    # Write mode: prune orphans, then write everything.
    for rel in orphans:
        os.remove(os.path.join(ROOT, rel))
    for rel, content in sorted(files.items()):
        path = os.path.join(ROOT, rel)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(content)
    # Remove now-empty managed directories left by pruning.
    for d in MANAGED_DIRS:
        base = os.path.join(ROOT, d)
        for dirpath, _dirs, _names in os.walk(base, topdown=False):
            if os.path.isdir(dirpath) and not os.listdir(dirpath):
                os.rmdir(dirpath)

    n_agents, n_skills, n_cmds = len(list_agents()), len(list_skills()), len(list_commands())
    print(f"Generated {len(files)} adapter files from {n_agents} agents, "
          f"{n_skills} skills, {n_cmds} commands.")
    if orphans:
        print(f"Pruned {len(orphans)} stale file(s).")


if __name__ == "__main__":
    main()
